### PR TITLE
fix: anvil-zksync able to start even if the port is busy

### LINKED ISSUE #512: anvil-zksync is able to start even if the port is busy
If you start two instances of `anvil-zksync` without specifying the port (e.g. in two terminals), the second instance would be able to start. However, in logs it outputs:

```
thread '09:40:57  INFO (3) 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
<unnamed>' panicked at 09:40:57  INFO (4) 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
src/main.rs:10109:40:57  INFO (5) 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
:48:
called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }09
```

...after which it _appears_ running. 

Probably, the panic isn't handled correctly during the API server spin up process.

### PR DESCRIPTION
**Pull request by dutterbutter**
# What :computer: 
* fixes: anvil-zksync able to start even if the port is busy, Closes #512 
* Bump CI versions for upload / download artifacts. See:
```
deprecated version of `actions/download-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

# Why :hand:
* Should be able to use fallback port if busy without panic

# Evidence :camera:

Screenshot 2025-01-16 at 10 04 52 AM

### CODE REVIEW

**Review by popzxc — APPROVED** [review]

File: crates/cli/src/main.rs [hunk 1]
```diff
@@ -317,10 +317,43 @@ async fn main() -> anyhow::Result<()> {
...
+                config.port = server.local_addr().port();
+                server_handles.push(server.run());
+            }
+            Err(err) => {
+                tracing::info!(
+                    "Failed to bind to address {}:{}: {}. Retrying with a different port...",
+                    host,
+                    config.port,
+                    err
+                );
```
Comment (itegulov) [inline crates/cli/src/main.rs:333]: Hmm, I don't think this is a good fallback. If I were running a tool in CI and saw this behaviour I would have been unpleasantly surprised.

Comment (popzxc) [reply crates/cli/src/main.rs:333]: Hm, indeed. I though for a second that `anvil` does that -- but no:

```
anvil
Error: Address already in use (os error 98)

Location:
    /home/runner/work/foundry/foundry/crates/anvil/src/lib.rs:229:28
```

I guess we have to replace the fallback with just error propagation.
